version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html
permissions:
  - object: /usr/share/nginx/html
    owner: root
    group: root
    mode: 755
hooks:
  AfterInstall:
    - location: scripts/restart_server.sh
      timeout: 300
      runas: root